const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {IDBFactory}=require('fake-indexeddb');
const code=fs.readFileSync('storage.js','utf8');
function browser(db=new IDBFactory(),ls=new Map(),quota=false){const window={};vm.runInNewContext(code,{window,indexedDB:db,structuredClone,Date,localStorage:{getItem:k=>ls.get(k)||null,setItem:(k,v)=>{if(quota&&v.length>50)throw Error('Quota');ls.set(k,v)}}});return {api:window.FoodJarStorage,db,ls}}
const data={profile:{jarName:'保留的罐子'},meals:[{id:'one',price:120,image:'data:image/png;base64,AAAA'}],budgets:{'2026-09':8000}};
test('fresh page and updated code retain saved meals, photos and budgets',async()=>{const a=browser();await a.api.read();await a.api.write(data);const b=browser(a.db,a.ls);assert.deepEqual(await b.api.read(),data);assert.equal(b.api.status.mirror,true)});
test('missing primary database recovers the full checkpoint before any empty state is written',async()=>{const a=browser();await a.api.read();await a.api.write(data);const b=browser(new IDBFactory(),a.ls);assert.deepEqual(JSON.parse(JSON.stringify(await b.api.read())),data);assert.equal(b.api.status.recovered,true);const c=browser(b.db,b.ls);assert.deepEqual(await c.api.read(),data)});
test('stale tab cannot overwrite newer records; an intentional deletion survives reopening',async()=>{const a=browser();await a.api.read();await a.api.write(data);const b=browser(a.db,a.ls);await b.api.read();const empty={...data,meals:[]};await a.api.write(empty);await assert.rejects(b.api.write(data),/STALE_STATE/);const c=browser(a.db,a.ls);assert.deepEqual(await c.api.read(),empty);const recovered=browser(new IDBFactory(),a.ls);assert.equal((await recovered.api.read()).meals.length,0)});
test('checkpoint quota failure keeps the database save and blocks stale fallback if primary is later lost',async()=>{const a=browser(undefined,undefined,true);await a.api.read();await a.api.write(data);assert.equal(a.api.status.mirror,false);assert.deepEqual(await a.api.read(),data);const b=browser(new IDBFactory(),a.ls);await assert.rejects(b.api.read(),/CHECKPOINT_UNAVAILABLE/)});
test('database open failure rejects instead of returning an empty jar',async()=>{const a=browser({open(){throw Error('storage blocked')}});await assert.rejects(a.api.read(),/storage blocked/);await assert.rejects(a.api.read(),/storage blocked/)});
